authentication/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views
from authentication import views as l_views
from authentication.views import (
    login,
    register,
    logout,
    AuthenticationPasswordResetView
)

app_name = 'log'

urlpatterns = [
    path('password_reset/', AuthenticationPasswordResetView.as_view(extra_context = {'compa': 'compa'}), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(extra_context = {'compa': 'compa'}), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(extra_context = {'compa': 'compa'}, success_url = reverse_lazy('authentication:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(extra_context = {'compa': 'compa'}), name='password_reset_complete'),

    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('logout/', logout, name='logout'),
]

blog/urls.py
from django.urls import path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    # Public store
    path('blog', index, name="index"),
]

core/urls.py
# Django
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# Core
from core.views import cookies

urlpatterns = [
    path('admin/', admin.site.urls),

    # Public
    path('', include('home.urls', namespace="home")),
    path('', include('store.urls', namespace="store")),
    path('', include('contact.urls', namespace="contact")),
    path('', include('blog.urls', namespace="blog")),
    path('', include('events.urls', namespace="events")),
    # Cookies
    path('cookies', cookies, name="cookies"),
    
    # Django
    path('', include('authentication.urls', namespace="authentication")),
    path('', include('settings.urls', namespace="settings")),
    path('', include('users.urls', namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path
from store.views import *

app_name = 'store'

urlpatterns = [
    # Public store
    path('store', index, name="index"),
    path('store/<int:id_product>', seller_product, name="sellerproduct"),
    path('@<slug:store_name>', seller_store, name="sellerstore"),
    # Dashboard
    path('mystore/', mystore_index, name="mystore"),
    path('mystore/new', products_create, name="new"),
    path('mystore/<int:product_id>', product_edit, name="edit"),
]

templates/gijalan/header/header.html
{% load staticfiles %}
<header id="header-waypoint-sticky" class="header-main header-mobile-menu with-absolute-navbar">
    <div class="header-outer clearfix">
        <div class="header-inner">
            <div class="row shrink-auto-lg gap-0 align-items-center">
                <div class="col-5 col-shrink">
                    <div class="col-inner">
                        <div class="main-logo">
                            <a href="{% url 'home:index' %}"><img src="{% static 'assets/images/logo.png' %}" alt="images" /></a>
                        </div>
                    </div>
                </div>
                <div class="col-7 col-shrink order-last-lg">
                    <div class="col-inner">
                        <ul class="nav-mini-right">

                            {% if not request.user.is_authenticated %}
                            <li class="d-none d-sm-block">
                                <a href="{% url 'authentication:login' %}" data-keyboard="false">
                                    <span class="icon-font"><i class="fas fa-boxes"></i></span> Publicar producto
                                </a>
                            </li>

                            {% else %}
                            <li class="d-none d-sm-block">
                                <a href="{% url 'store:mystore' %}" data-keyboard="false">
                                    <span class="icon-font"><i class="fas fa-boxes"></i></span> Publicar producto
                                </a>
                            </li>
                            {% endif %}

                            {% if request.user.is_authenticated %}
                            <li class="d-block d-sm-none">
                                <a href="{% url 'store:mystore' %}" data-backdrop="static" data-keyboard="false">
                                    Publicar producto
                                </a>
                            </li>
                            {% else %}
                            <li class="d-block d-sm-none">
                                <a href="{% url 'authentication:login' %}" data-backdrop="static" data-keyboard="false">
                                    Publicar producto
                                </a>
                            </li>
                            {% endif %}
                            <li>
                                <button class="btn btn-toggle collapsed" data-toggle="collapse" data-target="#mobileMenu"></button>
                            </li>
                        </ul>
                    </div>
                </div>
                
                <div class="col-12 col-auto">
                    <div class="navbar-wrapper">
                        <div class="navbar navbar-expand-lg">
                            <div id="mobileMenu" class="collapse navbar-collapse"> 
                                <nav class="main-nav-menu main-menu-nav navbar-arrow">
                                    <ul class="main-nav">
                                        <li><a href="{% url 'home:index' %}">Inicio</a></li>
                                        <li><a href="{% url 'store:index' %}">Tienda</a></li>
                                        <li><a href="{% url 'events:index' %}">Eventos</a></li>
                                        <li><a href="{% url 'blog:index' %}">Blog</a></li>
                                        <li><a href="{% url 'contact:index' %}">Contacto</a></li>
                                    </ul>
                                </nav><!--/.nav-collapse -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>