blog/urls.py
from django.urls import path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    # Public store
    path('blog', index, name="index"),
]

core/urls.py
# Django
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# Core
from core.views import cookies

urlpatterns = [
    path('admin/', admin.site.urls),

    # Public
    path('', include('home.urls', namespace="home")),
    path('', include('store.urls', namespace="store")),
    path('', include('contact.urls', namespace="contact")),
    path('', include('blog.urls', namespace="blog")),
    path('', include('events.urls', namespace="events")),
    # Cookies
    path('cookies', cookies, name="cookies"),
    
    # Django
    path('', include('authentication.urls', namespace="authentication")),
    path('', include('settings.urls', namespace="settings")),
    path('', include('users.urls', namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path
from store.views import *

app_name = 'store'

urlpatterns = [
    # Public store
    path('store', index, name="index"),
    path('store/<int:id_product>', seller_product, name="sellerproduct"),
    path('@<slug:store_name>', seller_store, name="sellerstore"),
    # Dashboard
    path('mystore/', mystore_index, name="mystore"),
    path('mystore/new', products_create, name="new"),
    path('mystore/<int:product_id>', product_edit, name="edit"),
]

store/templates/products/models.py
from django.db import models

# Create your models here.

templates/gijalan/generic/product/product.html
<div class="col">
                
    <figure class="tour-grid-item-01">

        <a href="{% url 'store:sellerproduct' product.pk %}">
        
            <div class="image">
                <img data-src="{{STATIC_STORAGE_PATH}}{{product.image_one.name}}" class="lazyload" alt="Chiloé Island">
            </div>
            
            <figcaption class="content">
                <h5>{{product.name}}</h5>
                <ul class="item-meta">
                        <li>
                            <p class="font12">ID: {{product.pk}}</p>
                        </li>
                </ul>
                <ul class="item-meta">
                    <li>
                        <a href="{% url 'store:sellerstore' product.seller.username %}"><i class="elegent-icon-profile text-warning"></i> {{product.seller.username}}</a>
                    </li>
                    <li>
                        <i class="elegent-icon-pin_alt text-warning"></i> {{product.seller.userprofile.commune.name}}
                    </li>
                    <li>	
                        <div class="rating-item rating-sm rating-inline clearfix">
                            <div class="rating-icons">
                                <input type="hidden" class="rating" data-filled="rating-icon ri-star rating-rated" data-empty="rating-icon ri-star-empty" data-fractions="2" data-readonly value="0"/>
                            </div>
                        </div>
                    </li>
                </ul>
                <p class="mt-3">Precio <span class="h6 line-1 text-primary font16" data-price="{{product.price}}" name="products-price">${{product.price}}</span> <span class="text-muted mr-5"></span></p>
            </figcaption>
        
        </a>
        
    </figure>
    
</div>